// Generated by CoffeeScript 1.8.0
(function() {
  var gulp, shell;

  gulp = require('gulp');

  shell = require('gulp-shell');

  module.exports = function() {
    return gulp.task('deploy', shell.task(['sh ../../../deploy.sh']));
  };

}).call(this);
